server:
 port: 8081
spring:
 application:
  name: supermarket
 datasource:
  #url: jdbc:h2:mem:supermarket
  url: jdbc:h2:file:C:/Users/hdala/Documents/H2/supermarket
  driverClassName: org.h2.Driver
  username: sa
  password: 
 h2:
  console:
   enabled: true 
   path: /h2
 jpa:
  hibernate:
   #ddl-auto: create
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.H2Dialect
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER
#logging:
# level:
#  root: DEBUG